version: "3.9"
services:
  mano:
    container_name: swap
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/src/app
    ports: 
       - 3000:8080